/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import billes.Agent;
import billes.Bille;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;

/**
 *
 * @author Remynoschka
 */
public class Grille extends javax.swing.JPanel{

    private static final int CASE_SIZE = 50;
    private billes.Grille grille;

    /**
     * Creates new form Grille
     */
    public Grille(billes.Grille grille) {
        this.grille = grille;
        initComponents();
        setPreferredSize(new Dimension(grille.getH() * CASE_SIZE, grille.getW() * CASE_SIZE));
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // CADRILLAGE
        for (int l = 1; l < grille.getH(); l++) {
            g.drawLine(0, l * CASE_SIZE, getX() + getWidth(), l * CASE_SIZE);
        }
        for (int c = 1; c < grille.getW(); c++) {
            g.drawLine(c * CASE_SIZE, 0, c * CASE_SIZE, getY() + getHeight());
        }
        // BILLES
        g.setColor(new Color(139, 35, 35));
        for (Agent b : grille.getAgents()) {
            g.fillOval(((Bille) b).getX() * CASE_SIZE + CASE_SIZE / 4, ((Bille) b).getY() * CASE_SIZE + CASE_SIZE / 4, CASE_SIZE / 2, CASE_SIZE / 2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


}
