/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.util.Observable;
import java.util.Observer;
import modele.Main;

/**
 *
 * @author Remynoschka
 */
public class Fenetre extends javax.swing.JFrame implements Observer {

    private static final int CASE_SIZE = 10;
    private modele.Grille grille;

    /**
     * Creates new form Fenetre
     */
    public Fenetre(modele.Grille grille) {
        this.grille = grille;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grillePanel = new ihm.Grille(modele.Grille.GRILLE);
        jMenuBar1 = new javax.swing.JMenuBar();
        environnementMenu = new javax.swing.JMenu();
        newGridMenuItem = new javax.swing.JMenuItem();
        speedMenuItem = new javax.swing.JMenuItem();
        seuilSatisfactionItem = new javax.swing.JMenuItem();
        affichageMenu = new javax.swing.JMenu();
        pyramideMenuItem = new javax.swing.JMenuItem();
        graphePopMenuItem = new javax.swing.JMenuItem();
        ratioMenuItem = new javax.swing.JMenuItem();
        showSatisfactionMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Poissons et Requins");

        javax.swing.GroupLayout grillePanelLayout = new javax.swing.GroupLayout(grillePanel);
        grillePanel.setLayout(grillePanelLayout);
        grillePanelLayout.setHorizontalGroup(
            grillePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        grillePanelLayout.setVerticalGroup(
            grillePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        environnementMenu.setText("Environnement");

        newGridMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        newGridMenuItem.setText("Nouvelle Grille");
        newGridMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGridMenuItemActionPerformed(evt);
            }
        });
        environnementMenu.add(newGridMenuItem);

        speedMenuItem.setText("Modifier la vitesse");
        speedMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speedMenuItemActionPerformed(evt);
            }
        });
        environnementMenu.add(speedMenuItem);

        seuilSatisfactionItem.setText("Modifier le seuil de Satisfaction");
        seuilSatisfactionItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seuilSatisfactionItemActionPerformed(evt);
            }
        });
        environnementMenu.add(seuilSatisfactionItem);

        jMenuBar1.add(environnementMenu);

        affichageMenu.setText("Afficher");

        pyramideMenuItem.setText("Pyramide des Ages");
        pyramideMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyramideMenuItemActionPerformed(evt);
            }
        });
        affichageMenu.add(pyramideMenuItem);

        graphePopMenuItem.setText("Graphe de Population");
        graphePopMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphePopMenuItemActionPerformed(evt);
            }
        });
        affichageMenu.add(graphePopMenuItem);

        ratioMenuItem.setText("Ratio de Population");
        ratioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratioMenuItemActionPerformed(evt);
            }
        });
        affichageMenu.add(ratioMenuItem);

        showSatisfactionMenuItem.setText("Satisfaction");
        showSatisfactionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSatisfactionMenuItemActionPerformed(evt);
            }
        });
        affichageMenu.add(showSatisfactionMenuItem);

        jMenuBar1.add(affichageMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grillePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grillePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ratioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratioMenuItemActionPerformed
        modele.Grille.GRILLE.addObserver(new FenetreGraphiqueRatio("Ratio"));
    }//GEN-LAST:event_ratioMenuItemActionPerformed

    private void newGridMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGridMenuItemActionPerformed
        NewGridMenu m = new NewGridMenu(this, true);
        m.setVisible(true);
        if (m.getReturnStatus() == NewGridMenu.RET_OK) {
            this.grille = new modele.Grille(m.getHauteur(), m.getLargeur());
            this.grille.generateRandomCreaturePlacement();
            this.grille.addObserver(this);
            this.grillePanel.setGrille(grille);
            modele.Grille.GRILLE = this.grille;
            
            pack();
            
            repaint();
        }
    }//GEN-LAST:event_newGridMenuItemActionPerformed

    private void pyramideMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyramideMenuItemActionPerformed
        new PyramideAges().setVisible(true);
    }//GEN-LAST:event_pyramideMenuItemActionPerformed

    private void graphePopMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphePopMenuItemActionPerformed
        modele.Grille.GRILLE.addObserver(new FenetreGraphiquePopulation("Population"));
    
    }//GEN-LAST:event_graphePopMenuItemActionPerformed

    private void speedMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speedMenuItemActionPerformed
        SetSpeedMenu m = new SetSpeedMenu(this, true);
        m.setVisible(true);
        if (m.getReturnStatus() == SetSpeedMenu.RET_OK){
            Main.SPEED = m.getSpeed();
        }
    }//GEN-LAST:event_speedMenuItemActionPerformed

    private void seuilSatisfactionItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seuilSatisfactionItemActionPerformed
        SetSeuilSatisfactionMenu m = new SetSeuilSatisfactionMenu(this, true);
        m.setVisible(true);
        if (m.getReturnStatus() == SetSpeedMenu.RET_OK){
            Main.SEUIL_SATISFACTION = m.getSeuil();
        }
    }//GEN-LAST:event_seuilSatisfactionItemActionPerformed

    private void showSatisfactionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSatisfactionMenuItemActionPerformed
        this.grille.addObserver(new SatisfactionView());
    }//GEN-LAST:event_showSatisfactionMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu affichageMenu;
    private javax.swing.JMenu environnementMenu;
    private javax.swing.JMenuItem graphePopMenuItem;
    private ihm.Grille grillePanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem newGridMenuItem;
    private javax.swing.JMenuItem pyramideMenuItem;
    private javax.swing.JMenuItem ratioMenuItem;
    private javax.swing.JMenuItem seuilSatisfactionItem;
    private javax.swing.JMenuItem showSatisfactionMenuItem;
    private javax.swing.JMenuItem speedMenuItem;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        repaint();
    }
}
